export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
export const FETCH_TRANSACTION = 'FETCH_TRANSACTION';
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const FILTER_TRANSACTION = 'FILTER_TRANSACTION';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const SEND_EMAIL = 'SEND_EMAIL';
export const SEND_EMAIL_FAIL = 'SEND_EMAIL_FAIL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const VALIDATE_TOKEN = 'VALIDATE_TOKEN';
export const TOKEN_FALSE = 'TOKEN_FALSE';

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const FETCH_BUDGETS = 'FETCH_BUDGETS';
export const FETCH_BUDGET = 'FETCH_BUDGET';
export const CREATE_BUDGET = 'CREATE_BUDGET';
export const UPDATE_BUDGET = 'UPDATE_BUDGET';
export const DELETE_BUDGET = 'DELETE_BUDGET';
export const FILTER_BUDGET = 'FILTER_BUDGET';
export const FETCH_BUDGETS_FAIL = 'FETCH_BUDGETS_FAIL';
export const ERROR_SET_FALSE = 'ERROR_SET_FALSE';

export const FETCH_USERS = 'FETCH_USERS';
export const DELETE_USER = 'DELETE_USER';
export const CHANGE_USER_ROLE = 'CHANGE_USER_ROLE';

export const FETCH_ROLES = 'FETCH_ROLES';

export const GET_STATISTICS_BY_YEAR = 'GET_STATISTICS_BY_YEAR';
export const GET_STATISTICS_BY_CATEGORY = 'GET_STATISTICS_BY_CATEGORY';
export const GET_STATISTICS_FOR_INCOMES_BY_CATEGORY = 'GET_STATISTICS_FOR_INCOMES_BY_CATEGORY';

export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const MARK_AS_READ = 'MARK_AS_READ';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';